# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from elements_sdk.configuration import Configuration


class AlertPartialUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'message': 'str',
        'level': 'str',
        'is_open': 'bool',
        'closed_at': 'datetime'
    }

    attribute_map = {
        'name': 'name',
        'message': 'message',
        'level': 'level',
        'is_open': 'is_open',
        'closed_at': 'closed_at'
    }

    def __init__(self, name=None, message=None, level=None, is_open=None, closed_at=None, local_vars_configuration=None):  # noqa: E501
        """AlertPartialUpdate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._message = None
        self._level = None
        self._is_open = None
        self._closed_at = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if message is not None:
            self.message = message
        if level is not None:
            self.level = level
        if is_open is not None:
            self.is_open = is_open
        self.closed_at = closed_at

    @property
    def name(self):
        """Gets the name of this AlertPartialUpdate.  # noqa: E501


        :return: The name of this AlertPartialUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AlertPartialUpdate.


        :param name: The name of this AlertPartialUpdate.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def message(self):
        """Gets the message of this AlertPartialUpdate.  # noqa: E501


        :return: The message of this AlertPartialUpdate.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this AlertPartialUpdate.


        :param message: The message of this AlertPartialUpdate.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                message is not None and len(message) < 1):
            raise ValueError("Invalid value for `message`, length must be greater than or equal to `1`")  # noqa: E501

        self._message = message

    @property
    def level(self):
        """Gets the level of this AlertPartialUpdate.  # noqa: E501


        :return: The level of this AlertPartialUpdate.  # noqa: E501
        :rtype: str
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this AlertPartialUpdate.


        :param level: The level of this AlertPartialUpdate.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                level is not None and len(level) > 255):
            raise ValueError("Invalid value for `level`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                level is not None and len(level) < 1):
            raise ValueError("Invalid value for `level`, length must be greater than or equal to `1`")  # noqa: E501

        self._level = level

    @property
    def is_open(self):
        """Gets the is_open of this AlertPartialUpdate.  # noqa: E501


        :return: The is_open of this AlertPartialUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._is_open

    @is_open.setter
    def is_open(self, is_open):
        """Sets the is_open of this AlertPartialUpdate.


        :param is_open: The is_open of this AlertPartialUpdate.  # noqa: E501
        :type: bool
        """

        self._is_open = is_open

    @property
    def closed_at(self):
        """Gets the closed_at of this AlertPartialUpdate.  # noqa: E501


        :return: The closed_at of this AlertPartialUpdate.  # noqa: E501
        :rtype: datetime
        """
        return self._closed_at

    @closed_at.setter
    def closed_at(self, closed_at):
        """Sets the closed_at of this AlertPartialUpdate.


        :param closed_at: The closed_at of this AlertPartialUpdate.  # noqa: E501
        :type: datetime
        """

        self._closed_at = closed_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertPartialUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AlertPartialUpdate):
            return True

        return self.to_dict() != other.to_dict()
