# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from elements_sdk.configuration import Configuration


class FileSizeDistributionItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'min': 'int',
        'max': 'int',
        'count': 'int',
        'percent': 'int',
        'average': 'int',
        'total': 'int'
    }

    attribute_map = {
        'min': 'min',
        'max': 'max',
        'count': 'count',
        'percent': 'percent',
        'average': 'average',
        'total': 'total'
    }

    def __init__(self, min=None, max=None, count=None, percent=None, average=None, total=None, local_vars_configuration=None):  # noqa: E501
        """FileSizeDistributionItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._min = None
        self._max = None
        self._count = None
        self._percent = None
        self._average = None
        self._total = None
        self.discriminator = None

        self.min = min
        self.max = max
        self.count = count
        self.percent = percent
        self.average = average
        self.total = total

    @property
    def min(self):
        """Gets the min of this FileSizeDistributionItem.  # noqa: E501


        :return: The min of this FileSizeDistributionItem.  # noqa: E501
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this FileSizeDistributionItem.


        :param min: The min of this FileSizeDistributionItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and min is None:  # noqa: E501
            raise ValueError("Invalid value for `min`, must not be `None`")  # noqa: E501

        self._min = min

    @property
    def max(self):
        """Gets the max of this FileSizeDistributionItem.  # noqa: E501


        :return: The max of this FileSizeDistributionItem.  # noqa: E501
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this FileSizeDistributionItem.


        :param max: The max of this FileSizeDistributionItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and max is None:  # noqa: E501
            raise ValueError("Invalid value for `max`, must not be `None`")  # noqa: E501

        self._max = max

    @property
    def count(self):
        """Gets the count of this FileSizeDistributionItem.  # noqa: E501


        :return: The count of this FileSizeDistributionItem.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this FileSizeDistributionItem.


        :param count: The count of this FileSizeDistributionItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and count is None:  # noqa: E501
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def percent(self):
        """Gets the percent of this FileSizeDistributionItem.  # noqa: E501


        :return: The percent of this FileSizeDistributionItem.  # noqa: E501
        :rtype: int
        """
        return self._percent

    @percent.setter
    def percent(self, percent):
        """Sets the percent of this FileSizeDistributionItem.


        :param percent: The percent of this FileSizeDistributionItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and percent is None:  # noqa: E501
            raise ValueError("Invalid value for `percent`, must not be `None`")  # noqa: E501

        self._percent = percent

    @property
    def average(self):
        """Gets the average of this FileSizeDistributionItem.  # noqa: E501


        :return: The average of this FileSizeDistributionItem.  # noqa: E501
        :rtype: int
        """
        return self._average

    @average.setter
    def average(self, average):
        """Sets the average of this FileSizeDistributionItem.


        :param average: The average of this FileSizeDistributionItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and average is None:  # noqa: E501
            raise ValueError("Invalid value for `average`, must not be `None`")  # noqa: E501

        self._average = average

    @property
    def total(self):
        """Gets the total of this FileSizeDistributionItem.  # noqa: E501


        :return: The total of this FileSizeDistributionItem.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this FileSizeDistributionItem.


        :param total: The total of this FileSizeDistributionItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and total is None:  # noqa: E501
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileSizeDistributionItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FileSizeDistributionItem):
            return True

        return self.to_dict() != other.to_dict()
