# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from elements_sdk.configuration import Configuration


class MediaFileContents(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'directories': 'list[MediaFile]',
        'bundles': 'list[MediaFileBundle]',
        'total': 'int'
    }

    attribute_map = {
        'directories': 'directories',
        'bundles': 'bundles',
        'total': 'total'
    }

    def __init__(self, directories=None, bundles=None, total=None, local_vars_configuration=None):  # noqa: E501
        """MediaFileContents - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._directories = None
        self._bundles = None
        self._total = None
        self.discriminator = None

        if directories is not None:
            self.directories = directories
        if bundles is not None:
            self.bundles = bundles
        self.total = total

    @property
    def directories(self):
        """Gets the directories of this MediaFileContents.  # noqa: E501


        :return: The directories of this MediaFileContents.  # noqa: E501
        :rtype: list[MediaFile]
        """
        return self._directories

    @directories.setter
    def directories(self, directories):
        """Sets the directories of this MediaFileContents.


        :param directories: The directories of this MediaFileContents.  # noqa: E501
        :type: list[MediaFile]
        """

        self._directories = directories

    @property
    def bundles(self):
        """Gets the bundles of this MediaFileContents.  # noqa: E501


        :return: The bundles of this MediaFileContents.  # noqa: E501
        :rtype: list[MediaFileBundle]
        """
        return self._bundles

    @bundles.setter
    def bundles(self, bundles):
        """Sets the bundles of this MediaFileContents.


        :param bundles: The bundles of this MediaFileContents.  # noqa: E501
        :type: list[MediaFileBundle]
        """

        self._bundles = bundles

    @property
    def total(self):
        """Gets the total of this MediaFileContents.  # noqa: E501


        :return: The total of this MediaFileContents.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this MediaFileContents.


        :param total: The total of this MediaFileContents.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and total is None:  # noqa: E501
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediaFileContents):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MediaFileContents):
            return True

        return self.to_dict() != other.to_dict()
