# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from elements_sdk.configuration import Configuration


class ProxyProfile(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'resolution': 'str',
        'rate_control': 'int',
        'crf': 'int',
        'bitrate': 'int',
        'audio_bitrate': 'int',
        'variants_limit': 'int',
        'enable_realtime_read': 'bool',
        'enable_dense_filmstrip': 'bool',
        'enable_watermark': 'bool',
        'watermark_image': 'str',
        'watermark_position': 'int',
        'watermark_opacity': 'float',
        'watermark_size': 'float',
        'lut': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'resolution': 'resolution',
        'rate_control': 'rate_control',
        'crf': 'crf',
        'bitrate': 'bitrate',
        'audio_bitrate': 'audio_bitrate',
        'variants_limit': 'variants_limit',
        'enable_realtime_read': 'enable_realtime_read',
        'enable_dense_filmstrip': 'enable_dense_filmstrip',
        'enable_watermark': 'enable_watermark',
        'watermark_image': 'watermark_image',
        'watermark_position': 'watermark_position',
        'watermark_opacity': 'watermark_opacity',
        'watermark_size': 'watermark_size',
        'lut': 'lut'
    }

    def __init__(self, id=None, name=None, resolution=None, rate_control=None, crf=None, bitrate=None, audio_bitrate=None, variants_limit=None, enable_realtime_read=None, enable_dense_filmstrip=None, enable_watermark=None, watermark_image=None, watermark_position=None, watermark_opacity=None, watermark_size=None, lut=None, local_vars_configuration=None):  # noqa: E501
        """ProxyProfile - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._resolution = None
        self._rate_control = None
        self._crf = None
        self._bitrate = None
        self._audio_bitrate = None
        self._variants_limit = None
        self._enable_realtime_read = None
        self._enable_dense_filmstrip = None
        self._enable_watermark = None
        self._watermark_image = None
        self._watermark_position = None
        self._watermark_opacity = None
        self._watermark_size = None
        self._lut = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.resolution = resolution
        if rate_control is not None:
            self.rate_control = rate_control
        self.crf = crf
        self.bitrate = bitrate
        if audio_bitrate is not None:
            self.audio_bitrate = audio_bitrate
        if variants_limit is not None:
            self.variants_limit = variants_limit
        if enable_realtime_read is not None:
            self.enable_realtime_read = enable_realtime_read
        if enable_dense_filmstrip is not None:
            self.enable_dense_filmstrip = enable_dense_filmstrip
        if enable_watermark is not None:
            self.enable_watermark = enable_watermark
        self.watermark_image = watermark_image
        if watermark_position is not None:
            self.watermark_position = watermark_position
        if watermark_opacity is not None:
            self.watermark_opacity = watermark_opacity
        if watermark_size is not None:
            self.watermark_size = watermark_size
        self.lut = lut

    @property
    def id(self):
        """Gets the id of this ProxyProfile.  # noqa: E501


        :return: The id of this ProxyProfile.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProxyProfile.


        :param id: The id of this ProxyProfile.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ProxyProfile.  # noqa: E501


        :return: The name of this ProxyProfile.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProxyProfile.


        :param name: The name of this ProxyProfile.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def resolution(self):
        """Gets the resolution of this ProxyProfile.  # noqa: E501


        :return: The resolution of this ProxyProfile.  # noqa: E501
        :rtype: str
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution):
        """Sets the resolution of this ProxyProfile.


        :param resolution: The resolution of this ProxyProfile.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                resolution is not None and len(resolution) > 1023):
            raise ValueError("Invalid value for `resolution`, length must be less than or equal to `1023`")  # noqa: E501

        self._resolution = resolution

    @property
    def rate_control(self):
        """Gets the rate_control of this ProxyProfile.  # noqa: E501


        :return: The rate_control of this ProxyProfile.  # noqa: E501
        :rtype: int
        """
        return self._rate_control

    @rate_control.setter
    def rate_control(self, rate_control):
        """Sets the rate_control of this ProxyProfile.


        :param rate_control: The rate_control of this ProxyProfile.  # noqa: E501
        :type: int
        """

        self._rate_control = rate_control

    @property
    def crf(self):
        """Gets the crf of this ProxyProfile.  # noqa: E501


        :return: The crf of this ProxyProfile.  # noqa: E501
        :rtype: int
        """
        return self._crf

    @crf.setter
    def crf(self, crf):
        """Sets the crf of this ProxyProfile.


        :param crf: The crf of this ProxyProfile.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                crf is not None and crf > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `crf`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                crf is not None and crf < -2147483648):  # noqa: E501
            raise ValueError("Invalid value for `crf`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._crf = crf

    @property
    def bitrate(self):
        """Gets the bitrate of this ProxyProfile.  # noqa: E501


        :return: The bitrate of this ProxyProfile.  # noqa: E501
        :rtype: int
        """
        return self._bitrate

    @bitrate.setter
    def bitrate(self, bitrate):
        """Sets the bitrate of this ProxyProfile.


        :param bitrate: The bitrate of this ProxyProfile.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                bitrate is not None and bitrate > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `bitrate`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                bitrate is not None and bitrate < -2147483648):  # noqa: E501
            raise ValueError("Invalid value for `bitrate`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._bitrate = bitrate

    @property
    def audio_bitrate(self):
        """Gets the audio_bitrate of this ProxyProfile.  # noqa: E501


        :return: The audio_bitrate of this ProxyProfile.  # noqa: E501
        :rtype: int
        """
        return self._audio_bitrate

    @audio_bitrate.setter
    def audio_bitrate(self, audio_bitrate):
        """Sets the audio_bitrate of this ProxyProfile.


        :param audio_bitrate: The audio_bitrate of this ProxyProfile.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                audio_bitrate is not None and audio_bitrate > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `audio_bitrate`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                audio_bitrate is not None and audio_bitrate < -2147483648):  # noqa: E501
            raise ValueError("Invalid value for `audio_bitrate`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._audio_bitrate = audio_bitrate

    @property
    def variants_limit(self):
        """Gets the variants_limit of this ProxyProfile.  # noqa: E501


        :return: The variants_limit of this ProxyProfile.  # noqa: E501
        :rtype: int
        """
        return self._variants_limit

    @variants_limit.setter
    def variants_limit(self, variants_limit):
        """Sets the variants_limit of this ProxyProfile.


        :param variants_limit: The variants_limit of this ProxyProfile.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                variants_limit is not None and variants_limit > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `variants_limit`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                variants_limit is not None and variants_limit < -2147483648):  # noqa: E501
            raise ValueError("Invalid value for `variants_limit`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._variants_limit = variants_limit

    @property
    def enable_realtime_read(self):
        """Gets the enable_realtime_read of this ProxyProfile.  # noqa: E501


        :return: The enable_realtime_read of this ProxyProfile.  # noqa: E501
        :rtype: bool
        """
        return self._enable_realtime_read

    @enable_realtime_read.setter
    def enable_realtime_read(self, enable_realtime_read):
        """Sets the enable_realtime_read of this ProxyProfile.


        :param enable_realtime_read: The enable_realtime_read of this ProxyProfile.  # noqa: E501
        :type: bool
        """

        self._enable_realtime_read = enable_realtime_read

    @property
    def enable_dense_filmstrip(self):
        """Gets the enable_dense_filmstrip of this ProxyProfile.  # noqa: E501


        :return: The enable_dense_filmstrip of this ProxyProfile.  # noqa: E501
        :rtype: bool
        """
        return self._enable_dense_filmstrip

    @enable_dense_filmstrip.setter
    def enable_dense_filmstrip(self, enable_dense_filmstrip):
        """Sets the enable_dense_filmstrip of this ProxyProfile.


        :param enable_dense_filmstrip: The enable_dense_filmstrip of this ProxyProfile.  # noqa: E501
        :type: bool
        """

        self._enable_dense_filmstrip = enable_dense_filmstrip

    @property
    def enable_watermark(self):
        """Gets the enable_watermark of this ProxyProfile.  # noqa: E501


        :return: The enable_watermark of this ProxyProfile.  # noqa: E501
        :rtype: bool
        """
        return self._enable_watermark

    @enable_watermark.setter
    def enable_watermark(self, enable_watermark):
        """Sets the enable_watermark of this ProxyProfile.


        :param enable_watermark: The enable_watermark of this ProxyProfile.  # noqa: E501
        :type: bool
        """

        self._enable_watermark = enable_watermark

    @property
    def watermark_image(self):
        """Gets the watermark_image of this ProxyProfile.  # noqa: E501


        :return: The watermark_image of this ProxyProfile.  # noqa: E501
        :rtype: str
        """
        return self._watermark_image

    @watermark_image.setter
    def watermark_image(self, watermark_image):
        """Sets the watermark_image of this ProxyProfile.


        :param watermark_image: The watermark_image of this ProxyProfile.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                watermark_image is not None and len(watermark_image) > 1023):
            raise ValueError("Invalid value for `watermark_image`, length must be less than or equal to `1023`")  # noqa: E501

        self._watermark_image = watermark_image

    @property
    def watermark_position(self):
        """Gets the watermark_position of this ProxyProfile.  # noqa: E501


        :return: The watermark_position of this ProxyProfile.  # noqa: E501
        :rtype: int
        """
        return self._watermark_position

    @watermark_position.setter
    def watermark_position(self, watermark_position):
        """Sets the watermark_position of this ProxyProfile.


        :param watermark_position: The watermark_position of this ProxyProfile.  # noqa: E501
        :type: int
        """

        self._watermark_position = watermark_position

    @property
    def watermark_opacity(self):
        """Gets the watermark_opacity of this ProxyProfile.  # noqa: E501


        :return: The watermark_opacity of this ProxyProfile.  # noqa: E501
        :rtype: float
        """
        return self._watermark_opacity

    @watermark_opacity.setter
    def watermark_opacity(self, watermark_opacity):
        """Sets the watermark_opacity of this ProxyProfile.


        :param watermark_opacity: The watermark_opacity of this ProxyProfile.  # noqa: E501
        :type: float
        """

        self._watermark_opacity = watermark_opacity

    @property
    def watermark_size(self):
        """Gets the watermark_size of this ProxyProfile.  # noqa: E501


        :return: The watermark_size of this ProxyProfile.  # noqa: E501
        :rtype: float
        """
        return self._watermark_size

    @watermark_size.setter
    def watermark_size(self, watermark_size):
        """Sets the watermark_size of this ProxyProfile.


        :param watermark_size: The watermark_size of this ProxyProfile.  # noqa: E501
        :type: float
        """

        self._watermark_size = watermark_size

    @property
    def lut(self):
        """Gets the lut of this ProxyProfile.  # noqa: E501


        :return: The lut of this ProxyProfile.  # noqa: E501
        :rtype: str
        """
        return self._lut

    @lut.setter
    def lut(self, lut):
        """Sets the lut of this ProxyProfile.


        :param lut: The lut of this ProxyProfile.  # noqa: E501
        :type: str
        """

        self._lut = lut

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProxyProfile):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProxyProfile):
            return True

        return self.to_dict() != other.to_dict()
