# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from elements_sdk.configuration import Configuration


class RDCHost(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'workstation': 'Workstation',
        'occupied': 'bool',
        'last_updated': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'workstation': 'workstation',
        'occupied': 'occupied',
        'last_updated': 'last_updated'
    }

    def __init__(self, id=None, workstation=None, occupied=None, last_updated=None, local_vars_configuration=None):  # noqa: E501
        """RDCHost - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._workstation = None
        self._occupied = None
        self._last_updated = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.workstation = workstation
        if occupied is not None:
            self.occupied = occupied
        if last_updated is not None:
            self.last_updated = last_updated

    @property
    def id(self):
        """Gets the id of this RDCHost.  # noqa: E501


        :return: The id of this RDCHost.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RDCHost.


        :param id: The id of this RDCHost.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def workstation(self):
        """Gets the workstation of this RDCHost.  # noqa: E501


        :return: The workstation of this RDCHost.  # noqa: E501
        :rtype: Workstation
        """
        return self._workstation

    @workstation.setter
    def workstation(self, workstation):
        """Sets the workstation of this RDCHost.


        :param workstation: The workstation of this RDCHost.  # noqa: E501
        :type: Workstation
        """
        if self.local_vars_configuration.client_side_validation and workstation is None:  # noqa: E501
            raise ValueError("Invalid value for `workstation`, must not be `None`")  # noqa: E501

        self._workstation = workstation

    @property
    def occupied(self):
        """Gets the occupied of this RDCHost.  # noqa: E501


        :return: The occupied of this RDCHost.  # noqa: E501
        :rtype: bool
        """
        return self._occupied

    @occupied.setter
    def occupied(self, occupied):
        """Sets the occupied of this RDCHost.


        :param occupied: The occupied of this RDCHost.  # noqa: E501
        :type: bool
        """

        self._occupied = occupied

    @property
    def last_updated(self):
        """Gets the last_updated of this RDCHost.  # noqa: E501


        :return: The last_updated of this RDCHost.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """Sets the last_updated of this RDCHost.


        :param last_updated: The last_updated of this RDCHost.  # noqa: E501
        :type: datetime
        """

        self._last_updated = last_updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RDCHost):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RDCHost):
            return True

        return self.to_dict() != other.to_dict()
